Sdemidov/pwa
monaco-software/zooma pull request #109
Opened 2021-04-27 06:36 UTC by sergey-demidov

На замену #103 
Таки решил починить PWA. Тестируем [тут](https://www.zooma-deluxe.ru/)

2021-04-27 17:25 UTC, romalenskiy requested changes

2021-04-27 17:25 UTC, romalenskiy commented on server/controllers/themeApi.ts
> +  app.get(`${API_PATH.USER_THEME}/:userId`, (req, res) => {
А почему тему юзера может получил кто угодно? Пример с использованием auth тут же выше, userId там берется после авторизации и явно его передавать не надо.

2021-04-27 17:25 UTC, romalenskiy commented on src/store/asyncActions.ts
> +    }
Если как-то по особому обрабатывать ошибку не хочеца, то try catch можно вообще убрать.

Дефолтная обработка ошибок (включая console.error(...)) сделана на уровне `src/api/core.ts`

2021-04-27 20:35 UTC, romalenskiy approved these changes

2021-04-29 13:09 UTC, spt30 approved these changes

2021-04-29 18:37 UTC, merged