Sdemidov/heroku
monaco-software/zooma pull request #26
Opened 2021-02-08 16:59 UTC by sergey-demidov

Resolve #18

Этот бранч подключен к хероку. Результат тут: https://zooma-deluxe.herokuapp.com/

2021-02-08 17:03 UTC, sergey-demidov commented
Да, npm-run-all не работает на хуке хаски. Заменил на олдскульный npm run &&

2021-02-08 19:34 UTC, romalenskiy commented on package.json
> +    "serve": "npx webpack serve",
Две команды одинаковые получаются `dev` и `serve`

2021-02-08 19:34 UTC, romalenskiy commented on package.json
> +    "lint": "^0.7.0",
А что это за пакет? Еще один линтер?🤔

2021-02-08 19:34 UTC, romalenskiy commented on package.json
> +    "typecheck": "^0.1.2"
И вот это тоже что-то странное

2021-02-08 19:35 UTC, romalenskiy commented on package.json
> +    "compression": "^1.7.4",
Давай зафиксируем версии у всех пакетов

2021-02-08 21:49 UTC, sergey-demidov commented on package.json
> +    "serve": "npx webpack serve",
Ну да. Дело в том, что нам надо освободить `start`, его хочет хероку. Ну а две одинаковые - потому что в разных местах видел и так и эдак. И чтобы понять, как запустить дев-сервер, приходится открывать package.json. А у нас - прокатит любая

2021-02-08 21:54 UTC, sergey-demidov commented on package.json
> +    "lint": "^0.7.0",
А, это я разбирался с `npm-run-all`. Он орал, что не может найти модуль lint. Ну я ему и дал, чего он хочет. Только дело было не в модуле. Он почему-то именно в хуке хаски начинает криво воспринимать npm скрипты. Надо это почистить

2021-02-08 21:55 UTC, sergey-demidov commented on package.json
> +    "compression": "^1.7.4",
Думаю - рано. Я бы сделал это на этапе ближе к сдаче проекта

2021-02-08 21:56 UTC, sergey-demidov commented on package.json
> +    "typecheck": "^0.1.2"
Да то же самое. Щас вычищу

2021-02-09 07:23 UTC, sergey-demidov commented
Добавил анимацию на победу

2021-02-09 15:18 UTC, spt30 requested changes
Большие компоненты плотно не смотрел — гляну после разбивки, иначе пока сбиваюсь при чтении

❗ Также давай как-то типами, картинкой или текстом опишем алгоритм, по которому работает сама игра. Условно входные и выходные данные для используемых частей. То есть превратим эту рисовалку в своеобразный черный ящик, чтобы больше при желании внести изменения в проект (например, добавить новый уровень или что-то такое), не приходилось вникать в то, как это работает, а можно было просто по примерам и описанию сделать.

2021-02-09 15:18 UTC, spt30 commented on .github/workflows/ci.yml
> +      - dev
А может добавим еще сборку на `push` в любую ветку?
Чтобы можно было сразу посмотреть, что сейчас сделано в ПРе и не сломает ли это чего-нибудь при влитии?

2021-02-09 15:18 UTC, spt30 commented on package.json
> +    "serve": "npx webpack serve",
Давай оставим `dev`
И в Readme можно добавить мануал по тому, как запустить локально и по тому, как, когда и куда будет собираться проект при пуше

2021-02-09 15:18 UTC, spt30 commented on server.js
> +const CSPHeader = `
Чтобы сохранять удобочитаемость, но не писать лишнего в сам заголовок, можно сделать так:
```
const CSPHeader = `
    default-src 'self';
    connect-src https://ya-praktikum.tech wss://ya-praktikum.tech;
    font-src https://fonts.gstatic.com https://fonts.googleapis.com;
    img-src 'self' blob: data: https://ya-praktikum.tech https://ssl.gstatic.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    script-src 'self' 'unsafe-inline';
`.trim();
```

2021-02-09 15:18 UTC, spt30 commented on server.js
> +  return next();
В миддлварах обычно не принято писать завершающий return
Просто `next()` достаточно

@romalenskiy поправь меня, если я не прав

2021-02-09 15:18 UTC, spt30 commented on server.js
> +process.on('SIGINT', () => shutDown());
можно просто передать функцию
```
process.on('SIGTERM', shutDown);
...
```

2021-02-09 15:18 UTC, spt30 commented on server.js
> +  });
👍

2021-02-09 15:18 UTC, spt30 commented on server.js
> +});
Может сделаем отдельную папку `middlewares/`, куда будем сразу складывать отдельно такие штуки?
А то бывают очень большие миддлвары, а хранить то там, то сям не очень хочется

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Back.tsx
> +import { store } from '../../../store/store';
Давай упорядочивать и отделять пустой строкой группы импортов:
- Внешние библиотеки
- Внутренние 
- css

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Back.tsx
> +  const level = store.getState().game.currentLevel;
давай использовать selectors
https://github.com/monaco-software/zooma/blob/dev/src/store/selectors.ts

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Back.tsx
> +  let image = new Image();
кажется, что эти паременные нужна только внутри хука и их можно объявить с помощью `const`

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Balls.tsx
> +import React, { FC, useEffect } from 'react';
ОЧЕНЬ большой компонент, перегруженный логикой
Видно, что примерно все из этого необходимо именно здесь

Предлагаю с такими компонентами поступать следующим образом:
- разбить на логически связанные части
- все, что можно вынести в отдельную утилиту, вынести и положить рядом в файлик
- все, что нельзя вынести (например, используется какое-то специфическое замыкание или завязка на жизненный цикл компонента) — вынести в отдельный компонент и обернуть им текущий

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Balls.tsx
> +  const dispatch = useDispatch();
договаривались использовать отдельный хук
https://github.com/monaco-software/zooma/blob/dev/src/hooks.ts#L4

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Balls.tsx
> +          alert('You win!)');
все такие заглушечные варианты (скорее всего тут будет красивое модальное окно потом, да?) предлагаю сразу выносить в отдельные методы или компоненты (пусть будет компонент из одной строчки, ничего страшного)
чтобы потом можно было подменить содержимое такого маленького компонента целиком, не боясь ничего разломать 

Single-responsibility principle: должна быть одна и только одна причина для внесения изменений в конкретный модуль

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Frog.tsx
> +  let state = BULLET_STATE.IDLE;
лягушку давай тоже препарируем на отдельные маленькие компоненты

2021-02-09 15:18 UTC, spt30 commented on src/features/game/Layers/Frog.tsx
> +  let state = BULLET_STATE.IDLE;
Существует специальный хук `useState()`
https://ru.reactjs.org/docs/hooks-overview.html#state-hook

2021-02-09 15:18 UTC, spt30 commented on src/features/game/constants.ts
> +  WIDTH= 800,
![Линтер](https://user-images.githubusercontent.com/31798669/107383308-b1b5d800-6b12-11eb-8339-b6a37cb5f3b9.jpg)

А вообще говоря, странно, что линтер это не подсветил
@romalenskiy точно все нормально с линтером?

2021-02-09 15:18 UTC, spt30 commented on src/features/game/levels.ts
> +const levels = Object.freeze([{
Хорошо бы типизировать такие вещи сразу

Давай заведем папочку common/ внутри src/, где будем хранить всякие типы, константы и пр.?

2021-02-09 15:18 UTC, spt30 commented on src/features/game/lib/ball.ts
> +    positionOffset = Math.floor(Math.random() * 60)
ты же написал утилиту специально для этих целей

2021-02-09 15:26 UTC, spt30 commented
@sergey-demidov @romalenskiy, а вообще говоря, что думаете насчет того, чтобы вынести всю часть про геймплей в отдельную библиотеку и подключать как зависимость в проект?

Кажется, тогда можно будет и линтеры по-разному настраивать, и независимо разворачивать это, и тестировать тоже

2021-02-09 15:42 UTC, sergey-demidov commented on server.js
> +const CSPHeader = `
@spt30, trim() там не поможет - нужно убрать вообще все переводы строки

2021-02-09 16:37 UTC, sergey-demidov commented on server.js
> +process.on('SIGINT', () => shutDown());
@spt30 Можно. Но так на него ругается парсер jetbrains. Видимо глюк какой-то, но я стараюсь не оствалять лишние предупреждения. Потом в этом ворохе можно важное пропустить
#
![Screenshot from 2021-02-09 19-33-48](https://user-images.githubusercontent.com/71117942/107395788-2f2b1980-6b0e-11eb-8961-97fd41b603fd.png)

2021-02-09 18:27 UTC, romalenskiy commented on server.js
> +  return next();
Я если честно не эксперт в экспрессе) В принципе не особо понимаю что тут происходит

2021-02-09 18:27 UTC, romalenskiy commented on src/features/game/constants.ts
> +  WIDTH= 800,
Проверю

2021-02-09 18:27 UTC, romalenskiy commented on src/features/game/Layers/Frog.tsx
> +  let state = BULLET_STATE.IDLE;
Как я понял, тут не нужен useState. Этот компонент не должен ререндериться вообще

2021-02-09 18:33 UTC, romalenskiy commented
> @sergey-demidov @romalenskiy, а вообще говоря, что думаете насчет того, чтобы вынести всю часть про геймплей в отдельную библиотеку и подключать как зависимость в проект?
> 
> Кажется, тогда можно будет и линтеры по-разному настраивать, и независимо разворачивать это, и тестировать тоже

Мне нравится идея, но я бы оставил это на дальнейшие спринты. Сейчас бы текущий пул задач успеть сделать)

2021-02-09 18:42 UTC, sergey-demidov commented
> @sergey-demidov @romalenskiy, а вообще говоря, что думаете насчет того, чтобы вынести всю часть про геймплей в отдельную библиотеку и подключать как зависимость в проект?
> 
> Кажется, тогда можно будет и линтеры по-разному настраивать, и независимо разворачивать это, и тестировать тоже

Хрен его знает.. Особого смысла не вижу. Если по линтеру - то да, я обычно другие правила использую, плюс fix-on-save. Поэтому отвык уже выглядывать где там какой пробел отсутствует. И да, я щас уперся в графику, а Рома вроде как делает остальное, но у меня ж и подугим частям есть задачи. Плюс общий стор с роутиногом, рейтиногом, левелами, авторизацией и еще хрен знает чем. Плюшек от разнесеня мало, а вот геморрой точно будет

2021-02-09 19:19 UTC, sergey-demidov commented on src/features/game/levels.ts
> +const levels = Object.freeze([{
Типизировал, но оставил в game/ . Просто не предсталяю, где оно еще может занадобиться

2021-02-09 19:25 UTC, sergey-demidov commented on src/features/game/Layers/Frog.tsx
> +  let state = BULLET_STATE.IDLE;
Да, сделано криво, это я не подумал. Но хук тут по-моему тоже не походит. Мне надо изменения отслеживать. следовательно - в подписку, правильно?

2021-02-09 19:30 UTC, sergey-demidov commented on package.json
> +    "serve": "npx webpack serve",
Ну хорошо. Кто я такой, чтобы спорить с большинством )

2021-02-10 09:57 UTC, spt30 commented on server.js
> +process.on('SIGINT', () => shutDown());
Ну ясно же, что с точки зрения работы кода ничего не поменяется

Если парсер ругается — это не повод усложнять код
Лучше оставить варнинг и хороший код, чем код хуже, но без варнинга
Еще лучше было бы разобраться, в чем проблема — но это вроде не критикал

2021-02-15 16:47 UTC, closed without merging

2021-02-15 16:48 UTC, sergey-demidov commented
Начал делать страницу с левелами - понял, что нужно править структуру game/levels.ts