Ralenskiy/authorization
monaco-software/zooma pull request #28
Opened 2021-02-11 16:11 UTC by romalenskiy

- Страница логина
- Страница регистрации
- Валидации для форм
- Подключил к апи

Вход | Регистрация
--- | ---
![image](https://user-images.githubusercontent.com/34841033/107662969-e2754900-6c9b-11eb-9449-915f807cfe60.png) | ![image](https://user-images.githubusercontent.com/34841033/107663322-4c8dee00-6c9c-11eb-8940-494a31d06780.png)

2021-02-12 14:05 UTC, spt30 requested changes

2021-02-12 14:05 UTC, spt30 commented on src/api/methods.ts
> +// TODO: написать общую обертку для хождения в АПИ и обработки ошибок
давай еще пока что сделаем общую обертку над всеми методами, которая будет ловить ошибки

2021-02-12 14:05 UTC, spt30 commented on src/api/schema.ts
> +export interface SignUpParams extends SignInParams{
пробела не хватает
явно что-то с линтером

2021-02-12 14:05 UTC, spt30 commented on src/api/schema.ts
> +export interface SignUpParams extends SignInParams{
или не хватает хука на прекоммит

2021-02-12 14:05 UTC, spt30 commented on src/common/validations.ts
> +import { FormFieldProps } from 'grommet';
годно, такие штуки надо выносить 👍

2021-02-12 14:05 UTC, spt30 commented on src/components/App/grommetTheme.ts
> +    round: '4px',
побуду дизайнером: ставь по возможности 3px для бордер-радиусов
так они будут выглядеть лаконично и для вертикально вытянутых, и для горизонтально вытянутых элементов

2021-02-12 14:05 UTC, spt30 commented on src/features/signin/SignIn.tsx
> +      });
Хранить обработку данных в компонентах — не ок. 

Давай сразу, раз уж прикручивали редакс, подумаем насчет работы с асинхронностью — прикрутим или redux-thunk, или redux-saga (есть еще redux-promise и redux-observable, но это почти всегда оверхед или неудобно)

Если хочешь совсем модно — посмотри в сторону react-query

2021-02-12 14:05 UTC, spt30 commented on src/common/langUtils.ts
> +export const getLang = (key: keyof typeof langPack): string => langPack[key];
getText

2021-02-12 19:56 UTC, romalenskiy commented on src/api/methods.ts
> +// TODO: написать общую обертку для хождения в АПИ и обработки ошибок
Хотел в отдельной задаче, но сделал сейчас. \+

2021-02-12 19:56 UTC, romalenskiy commented on src/api/schema.ts
> +export interface SignUpParams extends SignInParams{
Хз, другие ошибки ловит. Хук тоже есть.

Какое правило должно ловить это? Нашел такие 

- `@typescript-eslint/type-annotation-spacing`
- `@typescript-eslint/space-infix-ops`
- `@typescript-eslint/object-curly-spacing`

С объектами при этом все работает, а интерфейсы не ловит.

2021-02-12 19:56 UTC, romalenskiy commented on src/common/langUtils.ts
> +export const getLang = (key: keyof typeof langPack): string => langPack[key];
\+

2021-02-12 19:56 UTC, romalenskiy commented on src/components/App/grommetTheme.ts
> +    round: '4px',
Можешь поподробнее рассказать (может показать) в чем смысл? Почему именно 3, а не 2 или 37?

2021-02-12 19:56 UTC, romalenskiy commented on src/features/signin/SignIn.tsx
> +      });
thunk заюзал, привык уже к нему. \+

2021-02-12 20:06 UTC, romalenskiy commented on src/api/core.ts
> +          defaultErrorHandling && dispatch(appActions.setError(JSON.stringify(error)));
Как использовать этот error в интерфейсе подумаю в задача #14  
Думаю сделать что-то типа toast notification

2021-02-13 13:35 UTC, spt30 commented on src/api/core.ts
> +        .catch((error) => {
давай catch унесем в конец, после then

2021-02-13 13:35 UTC, spt30 commented on src/api/schema.ts
> +export interface SignUpParams extends SignInParams{
Слушай, да, ты прав, линтер это не ловит
Надо бы подумать над тем, чтобы подключить prettier
@romalenskiy @sergey-demidov Что думаете?

2021-02-13 13:35 UTC, spt30 commented on src/components/App/grommetTheme.ts
> +    round: '4px',
37 — это уже специфические

Я имел в виду, что когда выбираешь маленький бордер-радиус (выбираешь между 2, 3, 4, 5 px), при прочих равных лучше выбирать 3px
Он просто смотрится красивее и аккуратнее, чем другие, при любых соотношениях сторон

2px мало для больших, 4px много для маленьких, 5px вообще конское скругление в общем случае
А 3px красиво

2021-02-13 13:35 UTC, spt30 commented on src/components/App/grommetTheme.ts
> +    round: '4px',
Ну то есть нет какой-то декларации явной, это нигде не зафиксировано и не написано (наверное), но просто по опыту видел и сам использовал чаще всего 3px

2021-02-13 13:35 UTC, spt30 commented on src/hooks.ts
> +import { AppThunk, Dispatch } from './store/store';
поздновато, наверное, я об этом говорю, но давайте держать импорты в строгом порядке и отбивать группы импортов пустой строкой
есть плагин линтера import-order, можно его втащить и настроить, как надо (или оставить дефолтный)

я стараюсь придерживаться такого порядка:
- импорты пакетов
- компоненты
- утилиты, константы, типы, хуки, экшены
- css

2021-02-13 14:37 UTC, romalenskiy commented on src/api/schema.ts
> +export interface SignUpParams extends SignInParams{
Сам никогда не использовал, но вообще интересно попробовать. Завел на это задачку #30

2021-02-13 14:37 UTC, romalenskiy commented on src/api/core.ts
> +        .catch((error) => {
\+, зарефачил немного

2021-02-13 14:37 UTC, romalenskiy commented on src/components/App/grommetTheme.ts
> +    round: '4px',
\+

2021-02-13 14:37 UTC, romalenskiy commented on src/hooks.ts
> +import { AppThunk, Dispatch } from './store/store';
А какой в этом смысл вообще? Зачем смотреть на импорты? они проставляются автоматически IDE. И сворачиваются тоже
![image](https://user-images.githubusercontent.com/34841033/107852457-d4513500-6e21-11eb-8efb-d5c0c1cc8555.png)

2021-02-14 19:06 UTC, spt30 commented on src/hooks.ts
> +import { AppThunk, Dispatch } from './store/store';
чтобы явно понимать, что внутреннее, что внешнее, что откуда взялось
я достаточно часто смотрю на импорты

2021-02-14 19:06 UTC, spt30 approved these changes

2021-02-14 19:10 UTC, merged