Sdemidov/gameover
monaco-software/zooma pull request #32
Opened 2021-02-15 16:41 UTC by sergey-demidov

Fixes #17
Добавлен контент на страницу завершения игры. Поправлен конфиг вебпака

![Screenshot from 2021-02-15 19-31-57](https://user-images.githubusercontent.com/71117942/107972164-7e68c280-6fc4-11eb-8e92-bf771442bdd7.png)

2021-02-15 17:40 UTC, romalenskiy requested changes

2021-02-15 17:40 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> +  useAuth(true);
Там дефолтный параметр true, явно можно не указывать

2021-02-15 17:40 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> +  };
Эти константы смело можно вынести за пределы компонента, можно объявить их прямо перед компонентом.

2021-02-15 17:40 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> +                onClick={goToHome} label={getText('game_over_to_home_button')} />
Если форматируешь пропы компонента, то лучше уж делать это до конца. Так легче читается:
```tsx
<Button 
  className={block('button')}
  onClick={goToGame} 
  label={getText('game_over_to_game_button')} 
/>
```

2021-02-15 17:40 UTC, romalenskiy commented on src/features/gameOver/types.d.ts
> +declare module '*.png' {
Давай положим это в src/common/types.d.ts  
Ведь эта тема не привязана к конкретной фиче

2021-02-15 18:05 UTC, sergey-demidov commented on src/features/gameOver/types.d.ts
> +declare module '*.png' {
Если бы он оттуда работал, то я бы положил. Но он пашет, только если лежит на том же самом уровне. Я хз отчего.

2021-02-15 18:41 UTC, romalenskiy commented on src/features/gameOver/types.d.ts
> +declare module '*.png' {
Там конфликт имен походу, т.к. в src/common/ есть файл types.ts

Назови файл index.d.ts например

2021-02-15 18:42 UTC, romalenskiy commented on src/features/gameOver/types.d.ts
> +declare module '*.png' {
И кстати, не вижу в package.json пакет file-loader, не понимаю как у тебя вообще это завелось 🤔

2021-02-15 18:44 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> +                label={getText('game_over_to_home_button')} />
`/>` тоже на отдельную строчку 🤓

2021-02-15 18:47 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> -import { useAuth } from '../../hooks';
Теперь ты вообще убрал этот хук. Это намеренно?

2021-02-15 20:37 UTC, sergey-demidov commented on src/features/gameOver/GameOver.tsx
> -import { useAuth } from '../../hooks';
Ну видимо туплю

2021-02-15 20:42 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> -import { useAuth } from '../../hooks';
В том коменте я писал про то, что можно его вызывать без явной передачи true

2021-02-15 21:16 UTC, sergey-demidov commented on src/features/gameOver/GameOver.tsx
> -import { useAuth } from '../../hooks';
Не так понял

2021-02-15 21:18 UTC, sergey-demidov commented on src/features/gameOver/types.d.ts
> +declare module '*.png' {
Заработало с index. А file-loader видимо остался в node_modules от другой ветки

2021-02-16 14:36 UTC, romalenskiy commented on src/features/gameOver/GameOver.tsx
> +  };
Вот тут не понял. В предпоследнем коммите снова вернул внутрь компонента?)

2021-02-16 14:40 UTC, romalenskiy requested changes
Остался один момент и готов буду апрувить
https://github.com/monaco-software/zooma/pull/32#discussion_r576870425

2021-02-16 14:59 UTC, sergey-demidov commented on src/features/gameOver/GameOver.tsx
> +  };
Я тут попутал ветки и окна редактора. Надо спать иногда )

2021-02-16 15:02 UTC, romalenskiy approved these changes
Красота! 👍

2021-02-16 15:14 UTC, merged

2021-02-16 18:18 UTC, spt30 commented on src/common/index.d.ts
> +  export = value;
а что за конструкция такая `export = value`? как это вообще работает?

я никогда такого не встречал просто

2021-02-16 18:18 UTC, spt30 commented on src/features/gameOver/GameOver.tsx
> +    color: color,
можно использовать сокращенную запись

2021-02-16 18:29 UTC, sergey-demidov commented on src/common/index.d.ts
> +  export = value;
@spt30 Я сам хз. Эот копипаста [отсюда](https://stackoverflow.com/questions/51100401/typescript-image-import)

2021-02-16 18:36 UTC, spt30 commented on src/common/index.d.ts
> +  export = value;
тайпскрипт, что ты делаешь, прекрати.....
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

"я звоню в ментовку"

2021-02-16 18:38 UTC, romalenskiy commented on src/common/index.d.ts
> +  export = value;
В доке по вебпаку более привычный экспорт предлагают. Вроде должен работать  
https://webpack.js.org/guides/typescript/#importing-other-assets

2021-02-16 18:50 UTC, sergey-demidov commented on src/common/index.d.ts
> +  export = value;
Ну зато теперь понятно, что это равнозначные конструкции