Ralenskiy/forum UI
monaco-software/zooma pull request #36
Opened 2021-02-19 20:59 UTC by romalenskiy

Сделал форум. Интерфейс без апи, на моках.

Список тем | Создание темы
------------ | ------------------
![image](https://user-images.githubusercontent.com/34841033/108560543-f0ffd800-730d-11eb-97f2-6482411455a5.png) | ![image](https://user-images.githubusercontent.com/34841033/108560475-d6c5fa00-730d-11eb-9205-c2a201b8f92e.png)

Сообщения темы | Создание сообщения
------------------ | ------------------
![image](https://user-images.githubusercontent.com/34841033/108560609-10970080-730e-11eb-9fdf-2e08409cc4e0.png) | ![image](https://user-images.githubusercontent.com/34841033/108560830-61a6f480-730e-11eb-86ba-c6428fb015d5.png)

2021-02-21 10:51 UTC, sergey-demidov approved these changes, later dismissed
Маркдаун в учебном фоуме :muscle: а я думал - меня одного заносит. 
Как всегда отрисовано на 5+ :+1:

2021-02-21 10:51 UTC, sergey-demidov commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +    <Layer className={block()} style={{ maxWidth: 1000 }} position="bottom" onClickOutside={onClose} onEsc={onClose}>
Длиннннющая строчка. Неудобно будет редактировать

2021-02-21 10:51 UTC, sergey-demidov commented on src/pages/forum/Components/TopicMessageList/forum-topic-message-list.css
> +  background-color: #f3eeff;
Как бы нам вот такие штуки вынести в общий :root в виде переменных

2021-02-21 10:51 UTC, sergey-demidov commented on src/pages/forum/types.ts
> +  // Unix timestamp
А меня ругаешь за комменты, буквально описывающие код )

2021-02-22 13:08 UTC, spt30 requested changes

2021-02-22 13:08 UTC, spt30 commented on src/common/constants.ts
> +}>;
если ты не выносишь это в отдельный именованный интерфейс, незачем применять Partial, лучше написать явно

2021-02-22 13:08 UTC, spt30 commented on src/common/helpers.ts
> +export const getUserFullName = (user: UserObject) => {
а может деструктурировать сразу объект user?

2021-02-22 13:08 UTC, spt30 commented on src/components/App/App.tsx
> +            <Route path={ROUTES.FORUM_TOPIC} component={ForumTopic} />
может просто местами поменять? и не использовать exact

2021-02-22 13:08 UTC, spt30 commented on src/components/AvatarWithFallback/AvatarWithFallback.tsx
> +    <Avatar size={avatarSize} background="brand" {...restProps}>
а может в enum значения вынести?
и в `src/components/App/grommetTheme.ts` тоже

2021-02-22 13:08 UTC, spt30 commented on src/components/ButtonWithProgress/ButtonWithLoading.tsx
> +      <Button {...restProps} disabled={true} icon={<Spinner size={spinnerSize} color={spinnerColor} />} />
можно просто `disabled`, если линтер не запрещает

2021-02-22 13:08 UTC, spt30 commented on src/components/ButtonWithProgress/ButtonWithLoading.tsx
> +  );
можно в принципе один раз написать `return <Button...` и передавать туда значение disabled и icon в зависимости от условия

2021-02-22 13:08 UTC, spt30 commented on src/components/ButtonWithProgress/ButtonWithLoading.tsx
> +      <Button {...restProps} disabled={true} icon={<Spinner size={spinnerSize} color={spinnerColor} />} />
да, я помню, что мы говорили уже и про хуки, и про лямбды, но давай хоть компонент спиннера в переменную вынесем, а то совсем уж грязновато смотрится

2021-02-22 13:08 UTC, spt30 commented on src/components/ButtonWithProgress/ButtonWithLoading.tsx
> +      <Button {...restProps} disabled={true} icon={<Spinner size={spinnerSize} color={spinnerColor} />} />
`...restProps` лучше передавать всегда в конце
тогда если ты когда-нибудь захочешь в объекте restProps передавать пропсы, которые перебивают выставленные явно, меньше diff будет на гитхабе

2021-02-22 13:08 UTC, spt30 commented on src/components/MarkdownSafe/MarkdownSafe.tsx
> +  // https://github.com/probablyup/markdown-to-jsx#parsing-options
👍

2021-02-22 13:08 UTC, spt30 commented on src/components/MarkdownSafe/MarkdownSafe.tsx
> +    disableParsingRawHTML: true,
здесь я бы тоже местами поменял, чтобы можно было перебить если что

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/ForumHeader/ForumHead.tsx
> +        icon={<Add size="16px" />}
😢

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +    <Layer className={block()} style={{ maxWidth: 1000 }} position="bottom" onClickOutside={onClose} onEsc={onClose}>
можно линтер настроить, чтобы не больше 100 символов было
на моих 13" больше не вмещается, а остальные стандартные размеры экрана либо больше, либо совсем маргинальные

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +const block = b_.lock('forum-topic-message-input-modal');
forum-topic-message-input-modal-component-in-zooma-game-from-monaco-software-in-yandex-practicum-second-semester-practice

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +const block = b_.lock('forum-topic-message-input-modal');
давай придумывать более лаконичные названия
желательно не больше 3 слов, ну 4

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/MessageInputModal/forum-topic-message-input-modal.css
> +.forum-topic-message-input-modal__markdown-hint-highlight {
мне кажется, что это модификатор все же
какая-то тут немного неправильная по БЭМу разбивка в целом

как я вижу сейчас:
- есть блок инпута модалки — это ок
- есть элемент textarea-wrap — по сути это обертка над textarea и еще чем-то; лучше переименовать по смыслу
- если элемент textarea — это ок
- есть обертка над контролами, в которой пока текст и кнопка — это ок
- есть элемент markdown-hint — это ок, его можно переместить и будет норм
- есть элемент markdown-hint-highlight — это не ок, потому что его нельзя использовать не внутри элемента markdown-hint; я бы сделал это отдельным блоком сразу с модификатором; к тому же выглядит так, что такой блок потребуется еще не раз

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicMessageList/ForumTopicMessageList.tsx
> +const block = b_.lock('forum-topic-message-list');
давай сделаем 
```
const listBlock = b_.lock('forum-topic-message-list');
const messageBlock = b_.lock('forum-topic-message');
```

выглядит так, что они все же про разное — сообщение можно использовать и вне списка сообщений
например, запинить или выделить его; поместить внутри другого сообщения (переслать)

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicMessageList/forum-topic-message-list.css
> +  background-color: #f3eeff;
я бы еще стандартные отступы вынес тоже
типа 4px, 8px, 12px и так далее
а то все будет вразнобой, если это не из библиотеки компонент

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicMessageList/forum-topic-message-list.css
> +  margin: 10px 0 0 46px;
вот про этот разнобой говорю как раз
не понятно, откуда здесь 46px

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicMessageList/forum-topic-message-list.css
> +  line-height: 13px;
line-height лучше указывать все же коэффициентом, а не пикселями
а то можно ненароком забыть поменять потом

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicMessageList/forum-topic-message-list.css
> +  margin-left: 10px;
нет, кстати, ничего зазорного в том, чтобы общий стиль вынести отдельно
типа так:

```
.forum-topic-message-list__message-author-name,
.forum-topic-message-list__message-date {
  margin-left: 10px;
} 

.forum-topic-message-list__message-author-name {
  font-weight: 700;
}

.forum-topic-message-list__message-date {
  ...
```

Если он действительно общий согласно принципу единственной ответственности

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicsList/ForumTopicsList.tsx
> +const dateFormatter = new Intl.DateTimeFormat();
🤟

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Components/TopicsList/ForumTopicsList.tsx
> +        const url = ROUTES.FORUM_TOPIC.replace(':topicId', String(topic.id));
ой, а если я тут правильно понял, что ты хочешь сделать, то есть хук useParams внутри react-router-dom, который тебе достанет topicId из сматченного роута сразу

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/Forum/Forum.tsx
> +  const [isCreateTopicFormLoading, setIsCreateTopicFormLoading] = useState(false);
что-то как-то имена двух переменных из state больше, чем на первые 50% совпадают, тяжеловато читать

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/ForumTopic/ForumTopic.tsx
> +  const topicMessages = topic?.messages ?? [];
может сделать так, чтобы селектор возвращал сразу дефолтные значения?
и тут их сразу деструктурировать? 
а то сумасшествие какое-то: прям в компоненте размазана какая-то логика дефолтных значение одного и того же на 3 строчки

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/ForumTopic/ForumTopic.tsx
> +  const { topicId } = useParams<RouteParams>();
👍

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/ForumTopic/forum-topic.css
> +}
заметил что тут и в src/pages/forum/Forum/forum.css стили абсолютно одинаковые
это случайно так получилось или так будет всегда? если всегда, то лучше подумать над тем, как их объединить

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/types.ts
> +  createTimestamp: number;
createdAt как-то привычнее, не?

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/types.ts
> +  topic_name: string;
почему snake_case?

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/reducer.ts
> +    addTopic(state, { payload }: PayloadAction<Topic>) {
тогда уж `PayloadAction<ForumState['topics'][number]>`

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/reducer.ts
> +    addMessage(state, { payload }: PayloadAction<{ topicId: number; message: TopicMessage }>) {
го в отдельный интерфейс положим тип пейлоада? можно прям в этом же файле

2021-02-22 13:08 UTC, spt30 commented on src/pages/forum/reducer.ts
> +      const topicIndex = state.topics.findIndex((item) => item.id === payload.topicId);
а чем `Array.prototype.find()` не угодил?

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +    <Layer className={block()} style={{ maxWidth: 1000 }} position="bottom" onClickOutside={onClose} onEsc={onClose}>
До этого было 180. Сократил до 120, чтобы много мест не править.

2021-02-22 21:26 UTC, romalenskiy commented on src/components/MarkdownSafe/MarkdownSafe.tsx
> +    disableParsingRawHTML: true,
Смысл этого компонента в том чтобы забиндить значение пропа как раз. Если захочется его перебить, то надо использовать просто `<Markdown />`

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/Components/ForumHeader/ForumHead.tsx
> +        icon={<Add size="16px" />}
Вынес в переменную)

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/Components/MessageInputModal/ForumTopicMessageInputModal.tsx
> +const block = b_.lock('forum-topic-message-input-modal');
Не просто так же это делаю. `message-modal` слишком общее название, могут быть коллизии в стилях.

`input` из названия наверное можно убрать

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/Components/MessageInputModal/forum-topic-message-input-modal.css
> +.forum-topic-message-input-modal__markdown-hint-highlight {
Заиспользовал компонент из библиотеки, который добавляет font-weight: bold;

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/Components/TopicsList/ForumTopicsList.tsx
> +        const url = ROUTES.FORUM_TOPIC.replace(':topicId', String(topic.id));
Я хочу сгенерировать ссылку на топик вида `/forum/1`, где 1 это id топика.  
`useParams` тут кажется ни при чем

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/types.ts
> +  // Unix timestamp
Тут акцент на стандарте, в данном случае unix. Есть ведь еще iso 8601, например. А тип number об этом не расскажет

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/types.ts
> +  createTimestamp: number;
хз, мне timestamp привычно

2021-02-22 21:26 UTC, romalenskiy commented on src/pages/forum/ForumTopic/forum-topic.css
> +}
Вынес в общий компонент Container

2021-02-23 14:05 UTC, spt30 approved these changes

2021-02-23 14:05 UTC, spt30 commented on src/components/Container/Container.tsx
> +  const classNameString = className ? ` ${className}` : '';
иногда можно просто переопределить значение, оно все равно в замыкании: 
``className = className ? ` ${className}` : ''``

2021-02-23 14:05 UTC, spt30 commented on src/components/Container/Container.tsx
> +  const containerClass = `${block()}${classNameString}`;
может тут тоже хочется так сделать, но не уверен,,,,,,

2021-02-23 14:09 UTC, merged