Sdemidov/levelpage
monaco-software/zooma pull request #37
Opened 2021-02-20 15:19 UTC by sergey-demidov

Fixes #15 
- Добавлена страница с уровнями.
- Добавлены 2 уровня игры
- Исправлены ошибки при переходе между игрой и остальными страницами
- В `src/store/asyncActions.ts` добавлены заглушки для хранения данных об открытых уровнях
- Добавлено кэширование изображений в класс `Ball`. Есть прирост производительности, но на последнем этапе вылезли непонятные глюки - в массив индексов записано, что в ячейке есть изображение, но на самом деле там пусто, отчего тидет помаргивание шаров. 
- Добавлен вывод статистики по кэшированию

- Результат - [тут](https://zooma-dev.herokuapp.com/game/levels)

![Screenshot from 2021-02-20 18-10-21](https://user-images.githubusercontent.com/71117942/108600315-987d1900-73a7-11eb-96ab-b31e52d3b1b3.png)
![Screenshot from 2021-02-20 18-13-42](https://user-images.githubusercontent.com/71117942/108600320-a03cbd80-73a7-11eb-8cb4-22daee111f66.png)

2021-02-20 21:12 UTC, romalenskiy requested changes
Ух, тяжело такое ревьюить. Не стоило сюда впихивать оптимизации игровые, раз ПР про страницу уровней.

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Ui.tsx
> +      onClick={mouseClick} />
Зочем сломал форматирование

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +  const dispatch = useDispatch();
Вместо dispatch используем хук `useAction`

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +interface Props {
Удобно, когда интерфейс пропов расположен прямо перед компонентом. Смотришь на компонент — сразу видишь типы пропов

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +const getSign = (isAllowed: boolean) => {
Давай сделаем реакт-вэй, то есть превратим это в компонент. Тут только имя поменять на `Sign`. А на месте использования будет
```tsx
<Sign isAllowed={isAllowed} />
```

Вместо текущего
```tsx
{getSign(isAllowed)}
```

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +  // возвращаем функцию, если можно перейти
Комментарий странный, буквально описывает код ниже.  
Лучше объяснить зачем `history.push` завернут в `setTimeout`, потому что я не понял)

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +    return () => {
Не понял зачем возвращать функцию. Почему просто не выполнить действие? То есть так:
```tsx
  const goToLevel = () => {
    if (!isAllowed) { 
      return
    };

    dispatch(gameActions.setCurrentLevel(levelIndex));
    setTimeout(() => history.push(ROUTES.GAME), 0);
  };
```
Тогда по месту использования можно просто передать эту функцию вместо вызова:
 ```tsx
    <Card
      className={block( { 'disallowed': !isAllowed, 'selected': isSelected })}
      onClick={goToLevel}
      width="small"
      elevation={isSelected ? 'medium' : 'xsmall'}
    >
```

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +          Уровень {levelIndex + 1}
Унести текст в `getText`

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/Components/game-level.css
> +.game-level_selected {
Пустой селектор

2021-02-20 21:12 UTC, romalenskiy commented on src/features/gameLevels/GameLevels.tsx
> +        <Heading textAlign="center"
textAlign="center" на отдельную строчку, как остальные пропы. Так легче читается

2021-02-20 21:12 UTC, romalenskiy commented on src/store/asyncActions.ts
> +  fetchAllowedLevels: (): AppThunk<Promise<void>> => async (dispatch) => {
О, а давай это экшен унесем в `game/asyncActions.ts`. 

Это я что-то затупил и экшены по лидерборду сюда запихнул.  
Если будет желание, вынеси их в `lederboard/asyncActions.ts`. А если нет, то оставь рядом с ними TODO плиз, чтобы я не забыл это сделать.

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Game.tsx
> +  const timeoutRef = React.useRef<number>();
Тут кажется реф и не нужен, тебе ведь таймут этот понадобится только внутри эффекта. Можно так:
```tsx
useEffect(() => {
  let timeout;
  ...
  timeout = setTimeout(...);
  ...
  return () => {
    clearTimeout(timeout);
  }
}, [...])
```

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Balls.tsx
> +  const timeoutRef = React.useRef<number>();
Чет не то. Используешь один реф, чтобы записать разные таймауты. Один другой перезатирать будет. В итоге в эффекте ты очистишь только один таймаут.

Походу надо в рефе хранить массив таймаутов и пушить в него. А в эффекте проходиться по этому массиву и чистить все.

И го использовать просто `useRef`, а не `React.useRef,` чтобы консистентно было. Остальных хуков тоже касается.

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Balls.tsx
> +  const requestRef = React.useRef<number>();
Не вижу чтобы где-то происходила запись в этот реф, он не используется получается.

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Blackout.tsx
> +  const requestRef = React.useRef<number>();
А тут используешь один requestRef в нескольких местах

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Bullet.tsx
> +/** eslint prefer-const: "error" */
Не первый раз вижу, как ты это руками проставляешь в файлах. Давай занесем его в конфиг линтера, я только за.

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Bullet.tsx
> +  const dispatch = useDispatch();
useAction вместо dispatch

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Bullet.tsx
> +    requestRef.current = requestAnimationFrame(drawEffects);
Тоже самое про про перезатирание рефа. Твой эффект зависит от shotPath, то есть триггериться на каждое его изменение. А значит каждый раз будет создаваться новый requestAnimationFrame. Но в итоге ты очистишь только последний.

Можно же отписывать прямо в этом эффекте. Отписка будет происходить также на каждый триггер эффекта
```tsx

useEffect(() => {
    if (shotPath.length) {
      bullet.current.position = 0;
    }
    const timeout = requestAnimationFrame(drawEffects);

    return () => clearTimeout(timeout);
}, [shotPath]);
```

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Bullet.tsx
> +    timeoutRef.current = window.setTimeout(() => drawEffects(), fps(BULLET_SPEED));
Тоже самое

2021-02-20 21:12 UTC, romalenskiy commented on src/features/game/Layers/Combo.tsx
> +  const requestRef = React.useRef<number>();
Тут тоже, ну и в остальных компонентах

2021-02-20 21:13 UTC, romalenskiy commented
Страница уровней классно выглядит, за нее лайк! 👍

2021-02-20 21:30 UTC, sergey-demidov commented on src/features/game/Layers/Bullet.tsx
> +/** eslint prefer-const: "error" */
Тут дело в том, что он при разработке только мешает. У меня включен eslint --fix на сэйв и он зараза все подряд перезаписывает в const. А так сейчас это просто комментарий. Везде пишу let и не парюсь. Когда уже понятно, что там с логикой - убрал одну звездочку и автоматом все что не изменяетсяч становится const

2021-02-20 21:31 UTC, sergey-demidov commented on src/features/game/Layers/Ui.tsx
> +      onClick={mouseClick} />
Добаный автоформат. Проглядел

2021-02-20 22:05 UTC, sergey-demidov commented on src/features/gameLevels/Components/GameLevel.tsx
> +  // возвращаем функцию, если можно перейти
Для себя писал. Первый раз столкнулся с этой штукой, поэтому отметил. Дело в том, что если просто навесить даже пустую функцию на onClick то в браузере элемент отображается как кликабельный со всеми вытекающими. А мне надо было, чтоб неактивный левел был совсем неактивным. 

history.push завернут в setTimeout для того, чтобы поместить его в конец стэка вызовов. Мне нужно, чтобы он был вызван строго после того, как отработает setCurrentLevel

2021-02-20 22:15 UTC, sergey-demidov commented on src/features/gameLevels/Components/GameLevel.tsx
> +  // возвращаем функцию, если можно перейти
Хотя проверил - работает и без него. Привык я к асинхронщине

2021-02-20 22:16 UTC, sergey-demidov commented on src/features/gameLevels/Components/GameLevel.tsx
> +    return () => {
Написал выше про возвращаемую функцию

2021-02-21 01:32 UTC, sergey-demidov commented
> Ух, тяжело такое ревьюить. Не стоило сюда впихивать оптимизации игровые, раз ПР про страницу уровней.

Да оно само получилось. За страницей потянулись новые уровни, за ними пришлось переделать бэкграунд, потом решил поправить переходы ну и вобщем как-то так. Там этой оптимизации 20 строк в game/lib/Ball.ts на самом деле. А вот с выводом статистики на экран - это да. Это меня уже занесло.

2021-02-21 03:39 UTC, sergey-demidov commented on src/features/game/Layers/Bullet.tsx
> +    requestRef.current = requestAnimationFrame(drawEffects);
Ну вот этого я походу вообще не понимаю. Зачем от него вообще отписываться, тем более при каждом эффекте? По-моему он будет запущен и спокойно уйдет себе к чистильщику. А проблема может возникнуть только если между вызовом и запуском что-то произойдет. Например - переход на другую страницу. Ну так я и отписываюсь в 
useEffect(...,[])
Зачем лишние вызовы в других эффектах? Объясните мне ктонибудь, бестоковому..

2021-02-22 14:36 UTC, romalenskiy commented on src/features/gameLevels/Components/GameLevel.tsx
> +  // возвращаем функцию, если можно перейти
> Для себя писал. Первый раз столкнулся с этой штукой, поэтому отметил. Дело в том, что если просто навесить даже пустую функцию на onClick то в браузере элемент отображается как кликабельный со всеми вытекающими. А мне надо было, чтоб неактивный левел был совсем неактивным.

Воооот, это уже стоит написать в комментарий. Текущий этого не отражает. Что-то типа:  
"Громмет ставит автоматом `cursor: pointer;` карточкам, которым в `onClick` передается функция. Но если карточка disallowed, мне нужен `cursor: default;`. Поэтому для таких карточек в `onClick` передаю `undefined` вместо функции"

И можно еще явно `undefined` возвращать, чтобы прям прозрачно было.

2021-02-22 14:46 UTC, romalenskiy commented on src/features/game/Layers/Bullet.tsx
> +    requestRef.current = requestAnimationFrame(drawEffects);
Блин, это я нагнал, сорян 😬. Я не особо шарю за `requestAnimationFrame`, не приходилось его толком использовать. Почему-то думал, что он работает как `setInterval`, то есть триггерит коллбэк всякий раз, когда браузер сочтёт возможным осуществить анимацию. А он работает как `setTiemout`...

2021-02-23 12:47 UTC, romalenskiy requested changes

2021-02-23 12:47 UTC, romalenskiy commented on package.json
> +    "core-util-is": "^1.0.2",
Что это?

2021-02-23 12:47 UTC, romalenskiy commented on src/hooks.ts
> +};
Это получается копипаста с `useAction`. Давай сделаем красиво, прокачаем тип у `useAction` и удалим `useOperation`:
```ts
export const useAction = <P>(action: undefined extends P ? ActionCreatorWithoutPayload : ActionCreatorWithPayload<P>) => {
  const dispatch = useDispatch();

  return bindActionCreators(action, dispatch);
};
```

2021-02-23 12:54 UTC, sergey-demidov commented on src/hooks.ts
> +};
Красиво. Я чот не допер

2021-02-23 12:54 UTC, sergey-demidov commented on package.json
> +    "core-util-is": "^1.0.2",
А вот хз. Я теряюсь...

2021-02-23 13:46 UTC, romalenskiy approved these changes, later dismissed

2021-02-23 15:32 UTC, romalenskiy approved these changes

2021-02-23 15:36 UTC, merged