Sdemidov/account
monaco-software/zooma pull request #41
Opened 2021-02-25 17:47 UTC by sergey-demidov

Resolve #10 
Страница аккаунта
- добавлены формы профиля, аватара и смены пароля
- добавлена обработка ошибок запросов к API
- исправлены стили вывода ошибок полей форм

<details><summary>скрины</summary>

![profile1](https://user-images.githubusercontent.com/71117942/109194347-5fc7b000-77aa-11eb-9110-0260da06666a.png)
![profile2](https://user-images.githubusercontent.com/71117942/109194350-60604680-77aa-11eb-8e0b-2b6d6c7d53ff.png)
![profile3](https://user-images.githubusercontent.com/71117942/109194353-60604680-77aa-11eb-940f-21efa2849dd7.png)

</details>

2021-02-25 20:29 UTC, romalenskiy requested changes

2021-02-25 20:29 UTC, romalenskiy commented on src/api/core.ts
> -          console.error(error);
Я бы оставил console.error, чтобы не пихать его потом во все catch

2021-02-25 20:29 UTC, romalenskiy commented on src/pages/account/Account.tsx
> +    setShowPasswordModal(false);
А это разве не должно быть в then? Кажется логичным закрывать модалку, только если успех. А если ошибка — сразу дать возможность попробовать еще раз.

2021-02-25 20:29 UTC, romalenskiy commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
И это тоже в then

2021-02-25 20:29 UTC, romalenskiy commented on src/pages/account/Components/ChangePassword.tsx
> +      onEsc={() => setShowPasswordModal(false)}
Функцию в переменную надо, а то @ spt30  заругает 😳

2021-02-25 20:29 UTC, romalenskiy commented on src/pages/account/Components/ChangePassword.tsx
> +                onClick={() => setShowPasswordModal(false)}
Переменная

2021-02-25 20:37 UTC, sergey-demidov commented on src/api/core.ts
> -          console.error(error);
Сорян, это я погорячился. Перед ПР прохожу - удаляю все console.* debugger и прочую отладочную фигню, которую сам напихал. Этот ненароком попал под горячую руку. А тут он нужен, да.

2021-02-25 20:38 UTC, sergey-demidov commented on src/pages/account/Account.tsx
> +    setShowPasswordModal(false);
Ну да, наверное

2021-02-25 20:57 UTC, sergey-demidov commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
А вот тут не соглашусь - пароли надо сразу вычищать отовсюду

2021-02-25 21:20 UTC, romalenskiy commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
Зачем?) Например, пользователь ошибся в старом пароле. Ушел запрос в апи — пришла ошибка. Мы показали ошибку и зачем-то почистили новый пароль и confirm. А он так старался его придумывал, вводил...

2021-02-25 21:21 UTC, romalenskiy commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
Вот при закрытии модалки чистить можно, имею ввиду не только на submit

2021-02-25 22:01 UTC, sergey-demidov commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
> Зачем?) Например, пользователь ошибся в старом пароле. Ушел запрос в апи — пришла ошибка. Мы показали ошибку и зачем-то почистили новый пароль и confirm. А он так старался его придумывал, вводил...

Ибо нефиг. Это учетные данные, а не аватарка

2021-02-25 22:15 UTC, romalenskiy commented on src/pages/account/Account.tsx
> +    setPasswordFormFields(initPasswordFormFields);
Ну ладно...

2021-02-27 15:31 UTC, romalenskiy approved these changes, later dismissed

2021-02-27 16:21 UTC, spt30 commented on src/components/Notification/notification.css
> +  border-radius: 999px;
почему?

2021-02-27 16:21 UTC, spt30 commented on src/pages/account/Account.tsx
>  export const Account: FC = () => {
какой-то очень большой компонент получился, не хочешь подразбить?

2021-02-27 16:21 UTC, spt30 commented on src/pages/account/asyncActions.ts
> +export const asyncAccountActions = {
👍

2021-02-27 16:21 UTC, spt30 submitted a review, later dismissed

2021-02-27 16:29 UTC, sergey-demidov commented on src/components/Notification/notification.css
> +  border-radius: 999px;
Так органичней смотрится. Рома дал добро

2021-02-27 16:30 UTC, romalenskiy commented on src/components/Notification/notification.css
> +  border-radius: 999px;
@spt30 наверное имел ввиду, что можно написать `border-radius: 50%;` вместо непонятных `999px;`

2021-02-27 16:42 UTC, sergey-demidov commented on src/pages/account/Account.tsx
>  export const Account: FC = () => {
Да вроде все на своем месте. Есть точка маршрута и 3 формы. Там тока функции жирные

2021-02-27 16:42 UTC, sergey-demidov commented on src/pages/account/Account.tsx
>  export const Account: FC = () => {
Да вроде все на своем месте. Есть точка маршрута и 3 формы. Там тока функции жирные

2021-02-27 16:43 UTC, sergey-demidov commented on src/components/Notification/notification.css
> +  border-radius: 999px;
Или ты про 999? Так это просто радиус > любой из меньших сторон

2021-02-27 16:48 UTC, sergey-demidov commented on src/components/Notification/notification.css
> +  border-radius: 999px;
@romalenskiy 50% даст совсем другой эффект. Он скруглит по бОльшей стороне, получится овал дурной. 
А радиус в пикселях > любой из возможных сторон дас так раз то, что мне надо - скругление меньшей стороны

2021-02-27 16:51 UTC, sergey-demidov commented on src/components/Notification/notification.css
> +  border-radius: 999px;
Ну а сидеть его высчитывать незачем. Можно просто поставить заведомо бОльшее значение

2021-02-27 16:57 UTC, romalenskiy commented on src/components/Notification/notification.css
> +  border-radius: 999px;
А, понял

2021-02-28 11:20 UTC, spt30 commented on src/components/Notification/notification.css
> +  border-radius: 999px;
Мне скорее непонятно было, почему 999, а не 1000 например

2021-02-28 11:22 UTC, spt30 approved these changes

2021-02-28 11:22 UTC, spt30 approved these changes

2021-02-28 12:27 UTC, merged