Sdemidov/game sound
monaco-software/zooma pull request #62
Opened 2021-03-10 16:22 UTC by sergey-demidov

Апдейт игры. [результат](https://zooma-experimental.herokuapp.com/game)
- Изменен способ рендеринга шаров
- Сообщения перенсены в `langUtils`
- Добавлены
  + звуки
  + кнопки
  + индикация

![Screenshot from 2021-03-10 19-20-43](https://user-images.githubusercontent.com/71117942/110661587-c8188780-81d5-11eb-9144-c81a1c5c43eb.png)

2021-03-11 21:02 UTC, romalenskiy requested changes

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/reducer.ts
> +        asyncGameActions.sendVolume(state.volume).catch(console.error);
Асинхронным действиям не место в редьюсере. Редьюсер  — это чистая функция без сайд эфектов, которая просто выдает новое состояние стора.

Другими слова, синхронные экшены не должны вызывать асинхронные. А наоборот можно.

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/asyncActions.ts
> +
Лишний отступ

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/reducer.ts
> +        asyncGameActions.sendVolume(state.volume).catch(console.error);
И тут асинхронное

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/reducer.ts
> +export interface IGameButton {
Предлагаю вынести этот интерфейс в types.ts, чтобы разгрузить немного редьюсер

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/reducer.ts
>  interface Game {
И интерфейс стейта тоже

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/Layers/Buttons.tsx
> +    buttons.forEach( (button) => {
Пробел

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/components/decrease-volume-button.css
> +.decrease-volume-button {
В `src/pages/game/components/` чет свалка образовалась. Го распределим компоненты по папкам — рядом tsx и css

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/components/decreaseVolumeButton.tsx
> +export const DecreaseVolumeButton: FC<Props> = ({ ratio, x, y }) => {
Файл с этим компонентом со строчной буквы назван decreaseVolumeButton.tsx, надо с заглавной

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/constants.ts
> +export const LOCALSTORAGE_MUTE = '__monaco-software-zooma_mute_key_v1__';
(необязательно фиксить)  
Ключи для ls можно без префиксов называть. Все равно на каждый домен свой ls

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/lib/sound.ts
> +const loadFile = async (file: string): Promise<AudioBuffer | undefined> => {
Функция async, а await не используешь

2021-03-11 21:02 UTC, romalenskiy commented on src/pages/game/lib/sound.ts
> +import { store } from '@store/store';
Давай не использовать store напрямую, а передавать нужные вещи в аргументы функций

2021-03-12 09:27 UTC, romalenskiy commented on src/pages/game/lib/sound.ts
> +import { store } from '@store/store';
Не оч понял, ты не согласен?) Убрал, но не до конца

2021-03-12 21:16 UTC, sergey-demidov commented on src/pages/game/lib/sound.ts
> +import { store } from '@store/store';
Ну на самом деле это означает, что ночью таки надо спать ) А вобще - да, мне непонятно, почему из стора нельзя читать напрямую вне компонентов. Что не стОит писать - вполне себе согласен. Но вот читать-то что мешает?

2021-03-12 21:30 UTC, romalenskiy commented on src/pages/game/lib/sound.ts
> +import { store } from '@store/store';
Эти функции выглядят достаточно обособленно и +- универсально (как и остальное в папке `lib/`). Поэтому кажется логичными не завязывать их на стейт.

2021-03-12 21:31 UTC, romalenskiy approved these changes, later dismissed

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/Layers/Buttons.tsx
> +  ]);
```suggestion
  [...buttons]);
```

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/asyncActions.ts
> +      Number.isInteger(localStorageVolumeValue) &&
я бы заменил на `!Number.isNaN()`, так будет более очевидно, что тут хочется проверить

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/DecreaseVolumeButton/DecreaseVolumeButton.tsx
> +        height: `${BUTTON_RADIUS * 2 * ratio}px`,
можно вынести в переменные

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/DecreaseVolumeButton/DecreaseVolumeButton.tsx
> +export const DecreaseVolumeButton: FC<Props> = ({ ratio, x, y }) => {
какой красивый компонент получился 😍

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/FullscreenButton/FullscreenButton.tsx
> +export const FullscreenButton: FC<Props> = ({ ratio, x, y }) => {
две похожих кнопки, которые, кажется, будут похожи даже если захочется в них что-то поменять

можно вынести часть общей логики в HOC (или в хуки, но тут кажись они не очень красиво лягут, хотя, как знать)

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/FullscreenButton/fullscreen-button.css
> +.fullscreen-button {
и стили похожи, точно HOC нужен

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/IncreaseVolumeButton/IncreaseVolumeButton.tsx
> +export const IncreaseVolumeButton: FC<Props> = ({ ratio, x, y }) => {
три похожих

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/MuteButton/MuteButton.tsx
> +export const MuteButton: FC<Props> = ({ ratio, x, y }) => {
4

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/components/PauseButton/PauseButton.tsx
> +export const PauseButton: FC<Props> = ({ ratio, x, y }) => {
i++

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/lib/utils.ts
> +  document.body.appendChild(a);
не обязательно вставлять элемент в DOM-дерево, можно просто кликнуть

2021-03-13 13:36 UTC, spt30 commented on src/pages/game/lib/utils.ts
> +export function bufferDownloader(data: BlobPart, name: string) {
👍

2021-03-13 14:28 UTC, sergey-demidov commented on src/pages/game/asyncActions.ts
> +      Number.isInteger(localStorageVolumeValue) &&
Не, тут все чотка. Это должно быть именно целое число меду 0 и 100 включительно.

2021-03-14 03:25 UTC, spt30 commented on src/pages/game/asyncActions.ts
> +      Number.isInteger(localStorageVolumeValue) &&
ну parseInt тебе и так вернет целое
обычно просто при чтении кода взгляд цепляется за такие проверки

то есть я понимаю, что семантически твой вариант корректнее
но когда вот так бежишь глазами, останавливаешься на операциях, которые проверяют в числе прочего то, что уже и так проверено 
при рефакторинге потом будет проще понимать, какие тестовые случаи стоит рассмотреть

если коротко: чем уже проверка, тем лучше

2021-03-14 03:50 UTC, sergey-demidov commented on src/pages/game/components/FullscreenButton/FullscreenButton.tsx
> +export const FullscreenButton: FC<Props> = ({ ratio, x, y }) => {
Проблема в том, что они именно *похожи*. А начинаешь декомпозицию, и становится ясно, что там всей общей логики - стили и функция `handleMouseLeave`, да и та подвязана на индивидуальный экшн. И HOC туда тоже не ложится. Короче убрал классы, вынес стили во внешнюю функцию и на этом, думаю, надо остановиться.

2021-03-14 12:05 UTC, spt30 approved these changes

2021-03-14 12:35 UTC, merged