Ralenskiy/forum api
monaco-software/zooma pull request #90
Opened 2021-04-18 17:28 UTC by romalenskiy

Resolve #84
Resovle #85

- Добавил апи форума
- Добавил возможность отвечать на сообщения в темах форума (дерево сообщений)
- Порефкторил src/server.tsx (по мотивам #87)

Смотреть лучше по коммитам. В e1f0472 подвигал много файлов

<details>
  <summary>Скрин дерева сообщений</summary>

  ![image](https://user-images.githubusercontent.com/34841033/115154603-742a7980-a084-11eb-97b4-37c69cdcfff3.png)
</details>

2021-04-19 17:03 UTC, sergey-demidov requested changes

2021-04-19 17:03 UTC, sergey-demidov commented on package.json
>      "db:init": "until npx prisma migrate dev && npx prisma db seed --preview-feature; do echo ...; sleep 1; done",
![prisma-error](https://user-images.githubusercontent.com/71117942/115265788-3b4fda80-a140-11eb-81bc-ada7bc48e852.png)
Призма всем хороша, но есть один неприятный глюк - она при загрузке, как я понял, подтягивает бинарники SSL снаружи и периодически обламывается. Это вот скрин с последнего деплоя, получилось только с 5-го раза. Так что для CI тоже лучше сделать в цикле, как в `db:init`

2021-04-19 17:03 UTC, sergey-demidov commented on README.md
> +cp .env.sample .env
:+1:

2021-04-19 17:03 UTC, sergey-demidov commented on server/controllers/userApi.ts
> +export const userApi = (app: Express) => {
Не оч понятно откуда имя.. Может `themeApi`?

2021-04-19 17:03 UTC, sergey-demidov commented on server/middlewares/auth.ts
> +export const auth = (
:+1:

2021-04-19 17:03 UTC, sergey-demidov commented on src/pages/forum/Components/TopicsList/forum-topics-list.css
> +  color: var(--dark-1);
`dark-1` бы еще в `prisma/seed.js` переопределить посветлее/потемнее для разных подложек

2021-04-19 17:03 UTC, sergey-demidov commented on src/pages/forum/Components/TopicsList/forum-topics-list.css
> +  color: var(--dark-1);
И текст сообщений, кстати, тоже - в темной плохо видно. Либо, наоборот - убрать цвет, тада схема его сама сделает белым/черным
![movie3](https://user-images.githubusercontent.com/71117942/115274975-e618c680-a149-11eb-8e0d-0ceb3d6a2736.gif)

2021-04-19 17:03 UTC, sergey-demidov commented on webpack.ssr.js
> +    index: './server/client.tsx',
странно конечно смотрицца

2021-04-20 19:40 UTC, romalenskiy commented on webpack.ssr.js
> +    index: './server/client.tsx',
Не могу другое придумать. Есть предложения?

2021-04-20 19:44 UTC, romalenskiy commented on package.json
>      "db:init": "until npx prisma migrate dev && npx prisma db seed --preview-feature; do echo ...; sleep 1; done",
Винда в такое ваще не умеет. Чо делать?
![image](https://user-images.githubusercontent.com/34841033/115454807-dcff2680-a229-11eb-9bbe-80d74d4b5e36.png)

2021-04-20 20:22 UTC, sergey-demidov commented on webpack.ssr.js
> +    index: './server/client.tsx',
Может просто оставить его в src/

2021-04-20 20:26 UTC, sergey-demidov commented on package.json
>      "db:init": "until npx prisma migrate dev && npx prisma db seed --preview-feature; do echo ...; sleep 1; done",
Можно попробовать явно указать оболочку
`shell: bash`
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-running-a-script-using-bash
а если не прокатит - вынесем винду нахрен из CI. Она меня еще при жизни задолбала насмерть

2021-04-21 18:12 UTC, romalenskiy commented on webpack.ssr.js
> +    index: './server/client.tsx',
норм? в src/
![image](https://user-images.githubusercontent.com/34841033/115601308-4cd2e700-a2e6-11eb-9e94-869be7f7e80f.png)

2021-04-21 18:30 UTC, romalenskiy commented on package.json
>      "db:init": "until npx prisma migrate dev && npx prisma db seed --preview-feature; do echo ...; sleep 1; done",
Не сработало, убрал винду

2021-04-21 18:32 UTC, sergey-demidov approved these changes

2021-04-21 18:56 UTC, spt30 commented on server/controllers/forumApi.ts
> +    })();
может лучше на промисы переписать? красивее будет без IIFE

2021-04-21 18:56 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +  );
лучше это сделать один раз в корне файла
данные же не меняются

2021-04-21 18:56 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +    <html>
lang не хватает

2021-04-21 18:56 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +        <title>Zooma</title>
Deluxe

2021-04-21 18:56 UTC, spt30 commented on src/common/types.ts
> +};
🙈

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/Forum/Forum.tsx
> +    getTopics().finally(() => setIsTopicsLoading(false));
не оч понял
тут же не промис возвращается, функция синхронная, как это работает?

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/ForumTopic/ForumTopic.tsx
> +    messageParentIdRef.current = undefined;
null

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/ForumTopic/ForumTopic.tsx
> +        )}
тернарник

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/asyncActions.ts
> +            return getDeletedUser(userId);
я б для консистентности тут тоже промис возвращал

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/asyncActions.ts
> +    const message = await dispatch(apiCreateForumMessage(params));
диспатч сихнронный же

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/selectors.ts
> +  return messageTrees;
```suggestion
  return messageTrees.map((message) => {
    const children = allMessages.filter((item) => item.parentId === message.id);
    
    return {
      ...message,
      ...(children.length && { 
          children: getTrees(children, allMessages) 
      }),
    };
  });
```

2021-04-21 18:56 UTC, spt30 commented on src/pages/forum/selectors.ts
> +      return messageTrees.filter((item) => item.parentId === null);
```suggestion
      return getTrees(messages, messages).filter((item) => item.parentId === null);
```

2021-04-21 19:45 UTC, romalenskiy commented on server/ssr/ssrHandler.tsx
> +  );
Не, в stats.json лежат имена чанков с хешами, и они постоянно меняются при разработке
![image](https://user-images.githubusercontent.com/34841033/115608172-97586180-a2ee-11eb-9d7d-cdc0fb97bdfa.png)

2021-04-21 19:45 UTC, romalenskiy commented on src/common/types.ts
> +};
А шо не так?(
Вот у меня есть тип с параметрами запроса `GetForumMessagesParams`. Параметры передаются в query, то есть на бэк придут строками
![image](https://user-images.githubusercontent.com/34841033/115608531-0fbf2280-a2ef-11eb-8e10-c6d836029f67.png)

2021-04-21 19:45 UTC, romalenskiy commented on src/pages/forum/Forum/Forum.tsx
> +    getTopics().finally(() => setIsTopicsLoading(false));
Как это не промис? Вот мой асинхронный экшен (он же thunk) возвращает промис `Promise<void>`
![image](https://user-images.githubusercontent.com/34841033/115608902-85c38980-a2ef-11eb-9f19-f9e0f59dbc28.png)

2021-04-21 19:45 UTC, romalenskiy commented on src/pages/forum/ForumTopic/ForumTopic.tsx
> +    messageParentIdRef.current = undefined;
Зачем null? Мне дальше `number | undefined` понадобится для запроса в апи
![image](https://user-images.githubusercontent.com/34841033/115609195-e94db700-a2ef-11eb-9530-895a96836f83.png)

2021-04-21 19:45 UTC, romalenskiy commented on src/pages/forum/asyncActions.ts
> +            return getDeletedUser(userId);
Не понял. Функция `async`, промис и вернется.

При этом `getDeletedUser()` синхронная функция, `await` не нужен

2021-04-21 19:45 UTC, romalenskiy commented on src/pages/forum/asyncActions.ts
> +    const message = await dispatch(apiCreateForumMessage(params));
А экшен асинхронный (thunk), вернет промис

2021-04-21 19:45 UTC, romalenskiy commented on src/pages/forum/selectors.ts
> +  return messageTrees;
Про `.map` согл

Про `...(children.length &&...`:  
если children.length === 0, то (...0) === 💥

2021-04-21 19:48 UTC, romalenskiy commented on server/controllers/forumApi.ts
> +    })();
Если будет добавляться еще бизнес логика сюда (запросы чего-нибудь дополнительного, например) с промисами это все превратится в callback hell.

Пусть сразу будет везде IIFE с async/await

2021-04-21 19:51 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +  );
при разработке — да
во время работы приложения нет

я к тому, что лучше саму операцию вынести из функции прям в корень файла

2021-04-21 19:52 UTC, spt30 commented on src/common/types.ts
> +};
да я так, забавный хэлпер просто

2021-04-21 20:16 UTC, romalenskiy commented on server/ssr/ssrHandler.tsx
> +  );
Я не понимаю(  
readFileSync нужно делать каждый при вызове updateChunks  
updateChunks вызывается в проде только в корне файла, то есть повторно будет вызываться только при рестарте сервера

2021-04-21 20:41 UTC, spt30 commented on src/pages/forum/Forum/Forum.tsx
> +    getTopics().finally(() => setIsTopicsLoading(false));
<img width="475" alt="Снимок экрана 2021-04-22 в 00 56 15" src="https://user-images.githubusercontent.com/31798669/115613196-8c5cfb80-a305-11eb-95fd-8f507af59e17.png">

тут вот возвращается синхронная функция

2021-04-21 20:42 UTC, spt30 commented on src/pages/forum/asyncActions.ts
> +            return getDeletedUser(userId);
ну вот я и говорю, сделал бы getDeletedUser тоже условно асинхронной, чтобы Promise.all, который выше, принимал массив промисов, а не перемешанный массив промисов/результатов

2021-04-21 20:48 UTC, romalenskiy commented on src/pages/forum/Forum/Forum.tsx
> +    getTopics().finally(() => setIsTopicsLoading(false));
Ээм, ну да. Синхронная функция, которая диспатчит асинхронный экшен, который возвращает промис... В чем непонимание?

2021-04-21 20:55 UTC, romalenskiy commented on src/pages/forum/asyncActions.ts
> +            return getDeletedUser(userId);
Promise.all и будет принимать массив только промисов, потому что async любой return обернет в промис
![image](https://user-images.githubusercontent.com/34841033/115619677-dc839000-a2fc-11eb-9e5e-ed39eaf6fbcc.png)

2021-04-21 21:09 UTC, spt30 commented on src/pages/forum/selectors.ts
> +  return messageTrees;
ну тут вкусовщина
с точки зрения кода никакого 💥 не будет, отработает корректно (`{ ...0 }` вернет пустой объект)

но мне как-то субъективно приятнее наполнять объект сразу, а не с помощью тернарника и undefined или еще хуже кучи ifов

2021-04-21 21:25 UTC, spt30 commented on src/pages/forum/asyncActions.ts
> +    const message = await dispatch(apiCreateForumMessage(params));
не совсем: в управлении состоянием приложения смысл **диспетчера** как раз в том, чтобы **диспетчеризировать** события, независимо от того, синхронный или асинхронный у них side-effect
поэтому dispatch будет всегда синхронным, независимо от того, что ты передашь внутрь
<img width="692" alt="Снимок экрана 2021-04-22 в 02 25 11" src="https://user-images.githubusercontent.com/31798669/115622944-fa0f2480-a311-11eb-909b-97ef092d6e9d.png">

асинхронность в JS и управление состоянием приложения — обе традиционно достаточно тяжелые темы, поэтому их лучше бы разобрать подробно

по поводу управления состоянием я кидал как-то в слак ссылку на скринкасты Ильи Климова по этой теме, достаточно интересно

2021-04-21 21:38 UTC, romalenskiy commented on src/pages/forum/asyncActions.ts
> +    const message = await dispatch(apiCreateForumMessage(params));
Что ты хочешь этим сказать? Что код не рабочий, что из dipsatch не может вернуть промис?

Скрин из исходников редакса
![image](https://user-images.githubusercontent.com/34841033/115624189-f32ce580-a302-11eb-9d14-48021b181187.png)

2021-04-22 03:31 UTC, sergey-demidov commented on server/ssr/ssrHandler.tsx
> +  );
Ну тут походу реально недопонимание возникло. Это же не хук экспресса, который вызвается каждый раз при рендеринге, а функция... вызывается 1 раз при старте сервера и по сути нужна просто чтобы логику вынести из перегруженного server.tsx. Т.е. она и так уже 'в корне'

2021-04-22 12:22 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +  );
> updateChunks вызывается в проде только в корне файла 

да, это так
но в зависимости от какого-то условия (сейчас там только `isProduction`, но в теории может быть что угодно) вызывается на каждый рендеринг (не понятно, зачем, кстати)
![Снимок экрана 2021-04-22 в 17 20 48](https://user-images.githubusercontent.com/31798669/115713125-1604db80-a38f-11eb-9ef5-a5c710102eb0.png)

2021-04-22 12:23 UTC, spt30 commented on src/pages/forum/Forum/Forum.tsx
> +    getTopics().finally(() => setIsTopicsLoading(false));
Сор, вчера как-то упустил из внимания танки совсем, давно с ними не работал

2021-04-22 12:23 UTC, spt30 commented on src/pages/forum/asyncActions.ts
> +            return getDeletedUser(userId);
Ок, пусть будет так

2021-04-22 12:39 UTC, sergey-demidov commented on server/ssr/ssrHandler.tsx
> +  );
@spt30 Ну как бэ если это не продакшн, значит - девелопмент. А если девелопмент, то могла измениться сборка. Поэтому на каждый серверный рендеринг перечитываем чанки и пересобираем стили.

2021-04-22 12:42 UTC, sergey-demidov commented on server/ssr/ssrHandler.tsx
> +  );
ЗЫ - это вобще мой кусок кода, Рома его перенес только

2021-04-22 17:17 UTC, spt30 commented on server/ssr/ssrHandler.tsx
> +  );
ну в реальной жизни это может быть не development, а тестинг, например
к тому же, если я правильно понимаю, как сейчас настроен вотчинг, сервер перезапустится и заново выполнит корневой код в этом файле

ок, давайте оставим, если настаиваете

2021-04-22 17:17 UTC, spt30 approved these changes

2021-04-22 17:51 UTC, merged